name: TWICE TikTok to Facebook

on:
  schedule:
    - cron: "30 0 * * *" # 8:30 AM PH = 00:30 UTC
  workflow_dispatch: # allow manual run

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests yt-dlp

      - name: Run main.py
        env:
          PAGE_ACCESS_TOKEN: ${{ secrets.PAGE_ACCESS_TOKEN }}
          PAGE_ID: ${{ secrets.PAGE_ID }}
        run: python main.py

      - name: Commit changes (video_id_list.txt)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add downloads/video_id_list.txt
          git commit -m "update video id list [skip ci]" || echo "No changes to commit"
          git push
